сделал главную страницу и каталог
htmlacademy-htmlcss/1624733-device-36 pull request #2
Opened 2023-02-07 11:49 UTC by MagicHors

2023-02-09 09:31 UTC, eduardmavliutov requested changes
1. Первым делом при проверке решил закинуть разметку в валидатор: 
Помимо того, что у тегов img не указаны атрибуты src (сейчас на это забиваем, ибо это домашка 3 вебинар), есть и другие ошибки: незакрытые теги, отсутствие методов у форм и тд. Ссылка на валидатор https://validator.w3.org/#validate_by_input

2. Во всей разметке необходимо поправить отступы: должно быть 2 пробела. Проверь, что у тебя в среде разработки настроено все верно. Если используешь VSCode , то рекомендую установить вот это расширение https://marketplace.visualstudio.com/items?itemName=HookyQR.beautify Оно считается deprecated (устаревшим), но для форматирования html-файлов подойдет. После установки расширения жми 	 Windows: Alt+Shift+F macOS: ⌥+⇧+F и выбирай Beautify. Должно все отформатироваться.

2023-02-09 09:31 UTC, eduardmavliutov commented on catalog.html
> +          <a href="index.html" class="header-logo">
Согласно кодгайда, _class_ идет сразу после тега https://codeguide.academy/html-css.html#html-attr-order

2023-02-09 09:31 UTC, eduardmavliutov commented on catalog.html
> +        <div class="page-header__logo">
Зачем нам здесь обертка вокруг ссылки? 🤔

2023-02-09 09:31 UTC, eduardmavliutov commented on catalog.html
> +          <form class="form-search" action="" method="">
Нужно прописать значения для атрибутов action и method. 
`method="post" action="https://echo.htmlacademy.ru/"`

2023-02-09 09:31 UTC, eduardmavliutov commented on catalog.html
> +            <input class="form-search__search" type="search" placeholder="Поиск по сайту">
Несмотря на то, что в макете у поля для электронной почты нет лэйбла, в разметке он должен быть. Так, например, [скринридер](https://doka.guide/a11y/screenreaders/) сможет человеку озвучить название поля, которое нужно заполнить. Поэтому добавь input'у label, плиз. В целом стоит принять как догму: любой input всегда идет в паре с label'ом :) Это, кстати, [один](https://up.htmlacademy.ru/htmlcss/36/criteries#HTML-05) из критериев :)

[Статья про label](
https://htmlacademy.ru/blog/html/always-use-a-label)

2023-02-09 09:31 UTC, eduardmavliutov commented on catalog.html
> +          </div>
На странице каталога это место отличается, необходимо разметить согласно макета

<img width="792" alt="Снимок экрана 2023-02-08 в 15 29 31" src="https://user-images.githubusercontent.com/40761402/217530016-9ba73dbc-1c5e-425b-97cc-47809e5fff7a.png">

2023-02-09 09:31 UTC, eduardmavliutov commented on catalog.html
> +        <nav class="page-header__main-nav">
На странице может быть только одна главная навигация, то есть только один элемент `nav`, поэтому не нужно здесь заново открывать тег `nav`, просто не закрывай его и продолжай дальше разметку навигации.

2023-02-09 09:31 UTC, eduardmavliutov commented on catalog.html
> +            </li>
_Виртуальная реальность
Моноподы для селфи
Экшн-камеры
Фитнес-браслеты
Умные часы
Квадрокоптеры_
Это все элементы одного и того же списка - Каталога товаров, не нужно их разбивать на подсписки

2023-02-09 09:31 UTC, eduardmavliutov commented on catalog.html
> +      <div class="page-main__header">
Ты же даже класс назвал со словом _header_, так почему бы не использовать тег `<header>` в таком случае? :)

2023-02-09 09:31 UTC, eduardmavliutov commented on catalog.html
> +            <a class="breadcrumbs__link">Моноподы для селфи</a></li>
Предлагаю здесь сделать просто `<span>`, ибо тег `<a>` без атрибута href - это просто текст уже

2023-02-09 09:31 UTC, eduardmavliutov commented on catalog.html
> +        <div class="catalog-wrapper__filter-header">
Зачем нам этот div вокруг заголовка?

2023-02-09 09:31 UTC, eduardmavliutov commented on catalog.html
> +        <form class="form-catalog" action="https://echo.htmlacademy.ru/" method="">
Надо заполнить атрибут method

2023-02-09 09:31 UTC, eduardmavliutov commented on catalog.html
> +              </div>
Здесь нужно использовать input type="range", а не кнопки ;)
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/range

2023-02-09 09:31 UTC, eduardmavliutov commented on catalog.html
> +                </label>
Это у нас будут просто обычные `span`'ы без `input`'ов
<img width="250" alt="Снимок экрана 2023-02-09 в 11 22 13" src="https://user-images.githubusercontent.com/40761402/217756411-828d6be1-d366-4b89-8491-58094d33397b.png">

2023-02-09 09:31 UTC, eduardmavliutov commented on catalog.html
> +                <label class="form-catalog__label-checkbox">Чёрный</label>
Тут и далее для всех `input`'ов в форме
1) `input` и `label` никак не связаны, надо их связать
2) `input`'у надо задать атрибуты `name` и `value`

[Label element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label)

2023-02-09 09:31 UTC, eduardmavliutov commented on catalog.html
> +      <div class="catalog-wrapper__filter">
Здесь у нас начинается новая секция - товары с фильтрами, нужно разметить соответственно section + h2

Как вариант, можно обернуть фильтры в section и блок с сортировкой в section. Таким образом можно будет оставить секцию с товарами, которую ты разметил внизу

2023-02-09 09:31 UTC, eduardmavliutov commented on catalog.html
> +        </ul>
Это у нас не список, это у нас элемент `select`

2023-02-09 09:31 UTC, eduardmavliutov commented on catalog.html
> +              <div class="card-product__description-wrapper">
Для всех карточек товаров
1) Зачем нам здесь обертка в виде `div`'а? Карточка товара уже обернута в тег `<a>`
2) Заголовок всегда идет впереди, порядок элементов меняется через css
3) Не нужно использовать (на первом курсе html) тег picture, сейчас это лишнее переусложнение
4) Для цены подойдет обычный `span`, он как раз нужен для мелких фраз

2023-02-09 09:31 UTC, eduardmavliutov commented on catalog.html
> +            </div>
"Загрузить еще" - это кнопка, мы остаемся на той же странице. Обертка в виде `div`'а здесь не нужна

2023-02-09 09:31 UTC, eduardmavliutov commented on catalog.html
> +    <footer class="page-footer">
Футер можно поделить на секции при желании

2023-02-09 09:31 UTC, eduardmavliutov commented on catalog.html
> +      </div>
1) Зачем нам обертка в виде `div`'а вокруг логотипа?
2) Ссылке нужно добавить атрибут `href`, обычно клик по логотипу ведет на главную страницу

2023-02-09 09:31 UTC, eduardmavliutov commented on catalog.html
> +              <span class="visually-hidden">Телеграм</span>
Здесь и далее по каждой соц.сети: `<span>` должен быть внутри тега `<a>`, иначе у `<a>` не будет контента при отсутствии стилей, и, следственно, по ссылке нельзя будет кликнуть

2023-02-09 09:31 UTC, eduardmavliutov commented on index.html
> +            </ul>
1) Войти, сравнить, корзина - это все элементы одного списка, не нужно их дробить
2) Не нужно оборачивать в div. Чем проще разметка / код , тем лучше. В большинстве случаев можно добиться желаемого результата без лишних оберткок

2023-02-09 09:31 UTC, eduardmavliutov commented on index.html
> +        <nav class="page-header__main-nav">
Про повторяющиеся nav писал на странице каталога

2023-02-09 09:31 UTC, eduardmavliutov commented on index.html
> +      <h1 class="visually-hidden">Интернет-магазин гаджетов</h1>
Интернет-магазин гаджетов **Девайс** 😎

2023-02-09 09:31 UTC, eduardmavliutov commented on index.html
> +          <ol class="slider-promo__list">
Я бы все-таки не стал это делать списком , но если хочешь делать списком, то уже точно не `<ol>`, обычный `<ul>`

2023-02-09 09:31 UTC, eduardmavliutov commented on index.html
> +          </div>
А вот здесь уже можно и `ol` сделать, все-таки каждая кнопка - это активный элемент пагинации + надо в каждую кнопку текст вложить скрытый, иначе без стилей кнопка вообще будет без текста

2023-02-09 09:31 UTC, eduardmavliutov commented on index.html
> +                  </svg>
Здесь и далее для всех элементов каталога: подключать изображение здесь через `svg` - это излишне, нужен просто обычный `img`

2023-02-09 09:31 UTC, eduardmavliutov commented on index.html
> +                </div>
Здесь и далее для каждого таба: не нужно оборачивать в `div` , есть `li` , этого хватит

2023-02-09 09:31 UTC, eduardmavliutov commented on index.html
> +        <section class="page-main__delivery">
Доставку редкого товара можно разметить тегом aside, это своего рода реклама, которую можно разместить на любой странице

2023-02-09 09:31 UTC, eduardmavliutov commented on index.html
> +          </div>
1) div не нужен ;)
2) Внутри ссылки нужно оставить только текст,  изображения здесь декоративные, то есть подключаются через css

2023-02-09 09:31 UTC, eduardmavliutov commented on index.html
> +          <h3 class="company__title">О нас</h3>
Так все-таки h2 или h3?))

2023-02-09 09:31 UTC, eduardmavliutov commented on index.html
> +            <p class="contacts__text">Санкт-Петербург, набережная реки Карповки, 5, литера П. <br>+7 (812) 812-12-12</p>
Это у нас адрес, поэтому размечаем тегом address

2023-02-09 09:31 UTC, eduardmavliutov commented on index.html
> +              сб—вс: с 10:00 до 19:00</p>
Лучше сделать обычным списком с 2мя элементами: будни и выходные

2023-02-09 09:31 UTC, eduardmavliutov commented on index.html
> +          <h3 class="subscription__title">Подпишитесь на рассылку</h3>
В секции может быть только 1 заголовок, и тут у нас будет h2 .

2023-02-09 09:31 UTC, eduardmavliutov commented on index.html
> +          <form class="form-subscription" action="https://echo.htmlacademy.ru/" method="">
Нужно заполнить атрибут `method`

2023-02-09 09:31 UTC, eduardmavliutov commented on index.html
> +            <input class="form-subscription__email" type="email" placeholder="Ваш e-mail">
`<label>` нужен

2023-02-09 09:31 UTC, eduardmavliutov commented on index.html
> +      <div class="page-header__logo">
Про footer см. выше

2023-02-09 10:05 UTC, MagicHors commented on catalog.html
> +          <form class="form-search" action="" method="">
исправил

2023-02-09 12:21 UTC, MagicHors commented on catalog.html
> +          </div>
исправил

2023-02-09 13:58 UTC, MagicHors commented on index.html
> +          <h3 class="subscription__title">Подпишитесь на рассылку</h3>
не понял немного, h2 это же невидимый текст

2023-02-09 14:12 UTC, eduardmavliutov commented on index.html
> +          <h3 class="subscription__title">Подпишитесь на рассылку</h3>
Мы не видим элементы с классом visually-hidden, но суть таких элементов в том, чтобы скринридеры могли озвучить их. И получается, что для скринридера у нас 2 заголовка, также у нас 2 заголовка в одном логическом блоке документа, что тоже некорректно.

2023-02-09 14:23 UTC, MagicHors commented on catalog.html
> +      <div class="page-main__header">
это же не шапка сайта

2023-02-09 14:25 UTC, MagicHors commented on catalog.html
> +            <a class="breadcrumbs__link">Моноподы для селфи</a></li>
я исправил и добавил href) я когда писал не заметил этого

2023-02-09 14:27 UTC, MagicHors commented on catalog.html
> +        <div class="catalog-wrapper__filter-header">
удалил)

2023-02-09 16:52 UTC, eduardmavliutov commented on catalog.html
> +      <div class="page-main__header">
Причем здесь шапка сайта?

2023-02-09 16:56 UTC, eduardmavliutov commented on catalog.html
> +      <div class="page-main__header">
https://up.htmlacademy.ru/htmlcss/36/book/html/methodology-step-1

2023-02-13 04:52 UTC, MagicHors commented on catalog.html
> +      <div class="page-main__header">
то есть ты предлагаешь поменять div на headr?

2023-02-13 06:10 UTC, eduardmavliutov commented on catalog.html
> +      <div class="page-main__header">
Да

2023-02-13 06:58 UTC, MagicHors commented on catalog.html
> +              </div>
я хз как делал)))
по видео обучению смотрел, а видел фигу))
я по другому сейчас сделал, вроде норм будет
сейчас пулл реквест сделаю, проверирь пожалуйста

2023-02-13 07:20 UTC, MagicHors commented on catalog.html
> +        </ul>
вроде бы сделал

2023-02-13 07:40 UTC, eduardmavliutov commented on catalog.html
> +              </div>
Через интерфейс академии отправь на повторную проверку

2023-02-14 07:36 UTC, MagicHors commented on index.html
> +                  </svg>
может тогда убрать высоту и ширину, можно будет в CSS поставить всем одним разом?

2023-02-14 07:41 UTC, MagicHors commented on index.html
> +        <section class="page-main__delivery">
не понял

2023-02-14 07:46 UTC, MagicHors commented on index.html
> +          <h3 class="company__title">О нас</h3>
так h2 это невидимый раздел, как я делал до этого, а h3 уже как по макету

2023-02-14 07:50 UTC, MagicHors commented on index.html
> +          <h3 class="company__title">О нас</h3>
увидел коммент ниже, исправлю сейчас

2023-02-16 13:39 UTC, eduardmavliutov requested changes

2023-02-16 13:39 UTC, eduardmavliutov commented on catalog.html
> +             </div>
1) Не нужно оборачивать в div
2) Не нужно дробить на 2 списка, это все один список

2023-02-16 13:39 UTC, eduardmavliutov commented on catalog.html
> +           </div>
Не нужно оборачивать в div

2023-02-16 13:39 UTC, eduardmavliutov commented on catalog.html
> +         <div class="page-main__header">
Надо заменить div на header

2023-02-16 13:39 UTC, eduardmavliutov commented on catalog.html
> +            <h2 class="catalog-wrapper__heading">Фильтр:</h2>
Если у нас уже есть один невидимый заголовок с h2, то для видимого заголовка не нужно использовать h2, обычный `<p>` нужен

2023-02-16 13:39 UTC, eduardmavliutov commented on catalog.html
> +                    <input type="number" min="0" max="5000"  class="price-filter__input">
1) Class всегда должен идти первым после тега в соответствии с кодгайдом академии
2) Input'у надо добавить атрибут name

2023-02-16 13:39 UTC, eduardmavliutov commented on catalog.html
> +                    <input type="number" min="0" max="5000"  class="price-filter__input">
1) Class всегда должен идти первым после тега в соответствии с кодгайдом академии
2) Input'у надо добавить атрибут name

2023-02-16 13:39 UTC, eduardmavliutov commented on catalog.html
> +                    <input class="form-catalog__checkbox" type="checkbox" id="colorblack" checked>
Каждому полю для ввода надо добавить атрибут name
https://developer.mozilla.org/ru/docs/Web/HTML/Element/input#attr-name

2023-02-16 13:39 UTC, eduardmavliutov commented on catalog.html
> +           <h3 class="catalog-wrapper__heading">Сортировка:</h3>
Заголовок в секции есть ты же выше уже добавил h2, поэтому текст на 172 строке не нужно этот текст размечать h3

2023-02-16 13:39 UTC, eduardmavliutov commented on catalog.html
> +           <select class="sort-type">
Нужен label, select - это тоже интерактивный элемент

2023-02-16 13:39 UTC, eduardmavliutov commented on catalog.html
> +            <option class="sort-type__item">Популярные</option>
У каждого option'а должен быть атрибут value. Насколько я помню, это было в тренажерах по формам 
https://htmlacademy.ru/courses/46/run/15

2023-02-16 13:39 UTC, eduardmavliutov commented on catalog.html
> +           <a class="card-product__download-link" href="#">Загрузить ещЁ</a>
Это кнопка, мы остаемся на той же странице

2023-02-16 13:39 UTC, eduardmavliutov commented on catalog.html
> +                  <label class="price-filter__field">
У тебя отсутствует текст внутри label, нужно добавить, иначе же в нем просто нет смысла 🙂

2023-02-16 13:39 UTC, eduardmavliutov commented on catalog.html
> +                  <label class="price-filter__field">
Нужно добавить текст внутрь label'а

2023-02-16 13:39 UTC, eduardmavliutov commented on index.html
> +        <div class="page-header__logo">
Div на 13 строке нужно убрать

2023-02-16 13:39 UTC, eduardmavliutov commented on index.html
> +            <label class="form-search__label">
Нужно добавить текст внутрь label'а

2023-02-16 13:39 UTC, eduardmavliutov commented on index.html
> +            </ul>
Все еще жду 🙂

2023-02-16 13:39 UTC, eduardmavliutov commented on index.html
> +        <h3 class="company__title">О нас</h3>
Тут h2, это такая же секция, как и остальные, просто выглядит иначе 🙂

2023-02-16 13:39 UTC, eduardmavliutov commented on index.html
> +        <h3 class="contacts__title">Контакты</h3>
Тут тоже h2 🙂

2023-02-16 13:39 UTC, eduardmavliutov commented on index.html
> +          <label class="form-subscription__label">
Внутрь label'а нужно добавить текст

2023-02-16 14:22 UTC, MagicHors commented on catalog.html
> +           <h3 class="catalog-wrapper__heading">Сортировка:</h3>
на p заменил

2023-02-18 08:15 UTC, MagicHors commented on catalog.html
> +           <select class="sort-type">
я же по хорошему могу строку 172 заменить с Н3 на label. 
Как раз по нажатию на сортировку будет выбор критерий

2023-02-18 08:32 UTC, MagicHors commented on catalog.html
> +            <option class="sort-type__item">Популярные</option>
ну там написано:
"В атрибуте value тега <option> задаётся значение варианта ответа, а внутри этого тега располагается подпись варианта ответа.

Если при отправке формы у выбранного варианта задан value, то на сервер отправится значение этого атрибута. В противном случае будет отправлен текст подписи."
то есть не обязательный, я и не написал
исправил

2023-02-18 08:50 UTC, MagicHors commented on catalog.html
> +                  <label class="price-filter__field">
я тогда как раз "от/до" туда засунуть же смогу?))

2023-02-18 09:05 UTC, MagicHors commented on catalog.html
> +                  <label class="price-filter__field">
я не знаю что туда засунуть)

2023-02-18 09:10 UTC, MagicHors commented on index.html
> +        <h3 class="company__title">О нас</h3>
сложна)
я не понял

2023-02-19 07:25 UTC, eduardmavliutov commented on index.html
> +        <h3 class="company__title">О нас</h3>
Перефразирую: почему не h2?

2023-02-19 07:25 UTC, eduardmavliutov commented on catalog.html
> +           <h3 class="catalog-wrapper__heading">Сортировка:</h3>
🔥

2023-02-19 07:27 UTC, eduardmavliutov commented on catalog.html
> +            <option class="sort-type__item">Популярные</option>
Думаю, можно считать, что value - это всегда обязательный параметр, так как на сервер подобные вещи кириллицей не отправляются 🙂

2023-02-19 07:29 UTC, eduardmavliutov commented on catalog.html
> +                  <label class="price-filter__field">
В label мы указываем название того, что вводится в input'е, в данном случае в input'е вводится "цена от"

2023-02-21 07:17 UTC, merged